name: Deployment
on: push
jobs:
  Process:
    runs:
      using: 'node20'
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build Asset
        run: npm run build
      - name: Deploy
        run: echo "Deploying"

